### PR TITLE
Support building with Ninja on MacOSX. Fixes #65

### LINKED ISSUE #65: Support building with Ninja on MacOSX
It would be convenient to have support for building on MacOSX.
Xcode support is not necessary. Supporting Ninja is enough.

### PR DESCRIPTION
**Pull request by nevil**
I'm not sure if this is the best way to import apple_apsl, but I couldn't find a chromium git repo to add as a dependency...

### CODE REVIEW

**Comment by kqyang** [comment]
Hi nevil, thanks for working on MacOSX support! The changes look good with a couple of nit comments. 

Btw, have you reviewed contributing agreement: https://github.com/google/edash-packager/blob/master/CONTRIBUTING.md? Basically you'll need to sign a CLA, which gives us  permission to use and redistribute your contributions as part of the project. You may also want to add your name to [AUTHORS](https://github.com/google/edash-packager/blob/master/AUTHORS) and [CONTRIBUTORS](https://github.com/google/edash-packager/blob/master/CONTRIBUTORS) file.

**Comment by nevil** [comment]
I have signed the individual CLA.
Updating AUTHORS and CONTRIBUTORS just for this small change feels a bit much, but sure :-)

Pushed the changes after building and running *_unittest on MacOSX 10.11.2 and Ubuntu 15.10.

**Comment by kqyang** [comment]
Cool. I have tested and verified it work perfectly on my Mac as well. Thanks!

One last request,I think it is fine to just say MacOSX in commit message, otherwise good from my side.  Can you replace "MacOSX ninja build:" with "MacOSX:" in all the commit messages?

**Comment by nevil** [comment]
@kqyang 
I changed as suggested.
Just for safety, built and ran *_unittest on MacOSX 10.11.2 and Ubuntu 15.10 before pushing.

Thanks for the quick review!

**Comment by kqyang** [comment]
I have merged this pull request.
@nevil thanks for your work on MacOSX and thanks for the contribution to edash-packager project!

**Pull request closed without merging**
